title: "Alexandra McKillip"
logo: "/images/headshot.jpg"
description: >
  Master of Data Science Student at Rice University | TAMU Alum
  <br><br>
  <strong>Let's Connect:</strong>
  <br>
  [LinkedIn](https://www.linkedin.com/in/alexandra-mckillip-15171920a/)
  <br>
  [Email](mailto:alexandra.mckillip@rice.edu)
show_downloads: false
theme: jekyll-theme-minimal
