title: "Alexandra McKillip"
logo: "images/headshot.jpg"
description: >
  Industrial Engineer | MS Data Science @ Rice University
  <br><br>
  [LinkedIn](https://www.linkedin.com/in/alexandra-mckillip-15171920a/) | [Email](mailto:alexandra.mckillip@rice.edu)
show_downloads: false
theme: jekyll-theme-minimal
