title: "Alexandra McKillip"
logo: "/images/headshot.jpg"
description: >
  Master of Data Science Student at Rice University | TAMU Alum
  <br><br>
  <strong>Let's Connect:</strong>
  <br>
  <a href="https://www.linkedin.com/in/alexandra-mckillip-15171920a/">LinkedIn</a> | 
  <a href="mailto:alexandra.mckillip@rice.edu">Email</a>
show_downloads: false
theme: jekyll-theme-minimal
